### ISSUE TITLE
marker0 not in gazebodir

### ISSUE THREAD

**Issue by ohanoch** [mikaelarguedas/gazebo_models#3]
I ended up needing to move the marker0 directory from "gazebo_models/model" to gazebodir manually myself prior to running your python script -  otherwise I kept getting that what I was trying to copy in the script didn't exist.

I think you should either add in the README.md an explanation mentioning this or maybe add it to your python code.

Otherwise thanks for the great repo! It helped me a lot!

**Comment by mikaelarguedas** [comment]
Thanks @ohanoch for pointing it out. Can you please submit a PR to either add that step to the README or add the copy to the python script? thanks!

**Comment by ohanoch** [comment]
I am sorry for reviving something you probably forgot existed, and then asking you for help, but this is the first time I have been asked to make a pull request, and I am having problems.

I created a new branch and added the copying to the code, but after that the tutorial I am following says I should just git push and then deal with the push request on github, but while git pushing I get is that I don't have permissions. Can it be the case that you need to give me permissions to push and make a pull request?

**Comment by mikaelarguedas** [comment]
Indeed you don't have push access to the repository.
A common workflow on github is to fork the repository (top right corner) and then submit a Pull Request.
1. Fork the repository: this will create a copy of the repository under your name (and you will have write access to it).
1. Create a commit with your changes
1. Push your changes to **your** version of the repository:
- In the repository directory on your computer: list the remote repositories: `git remote -v`
- Add your version of the repository to the list: `git remote add <MYFORK> <URL of your version of the repository>`
- Now you should have a new remote called `<MYFORK>`
- Push your changes to your fork: `git push <MYFORK> <branch_name>`
1. Open a Pull Request using the github UI

**Comment by mikaelarguedas** [comment]
closed by #4
