### ISSUE TITLE
marker0's size is always default

### ISSUE THREAD

**Issue by JimmyDaSilva** [mikaelarguedas/gazebo_models#5]
Thanks @mikaelarguedas this saved me some time !
A very small issue : You always copy the model marker0 from the template without taking the size into account.
Result: Everything works fine, except my marker0 is not scaled.

Cheers,
Jimmy

**Comment by mikaelarguedas** [comment]
Thanks @JimmyDaSilva for reporting this. It looks like a regression of https://github.com/mikaelarguedas/gazebo_models/pull/4.
Can you check if #7 solves your issue ?
